name: Admin CI >> STAGING

on:
  pull_request:
    branches: [ staging ]
    paths:
      - "client-admin/*/**"
      - "client-admin/package*"
      - ".github/workflows/admin-integration.staging.yml"
      # ignore README

    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./client-admin
    
    timeout-minutes: 2
    
    strategy:
      matrix:
        node-version: [ 14.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: CHECK-OUT GIT REPOSITORY
      uses: actions/checkout@v2
      
    - name: USE NODE.JS ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: INSTALL PROJECT DEPENDENCIES (NPM CI)
      run: npm ci

    - name: BUILD ENV VARIABLES TO .env
      run: echo $'${{ secrets.ADMIN_ENV_STAGING}}' > .env

    - name: CHECK ENV VARIABLES IN .env
      run: cat .env
      
    - name: RUN BUILD
      run: npm run build --if-present
      env:
        CI: false