# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server CD >> STAGING

on:
  push:
    branches: [ staging ]
    paths:
      - "server/*/**"
      - "server/app.js"
      - "server/package*"
      
      # ignore README

    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./server
    
    timeout-minutes: 1
    
    strategy:
      matrix:
        node-version: [ 14.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: CHECK-OUT GIT REPOSITORY
      uses: actions/checkout@v2
      
    - name: USE NODE.JS ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: INSTALL PROJECT DEPENDENCIES (NPM CI)
      run: npm ci

    # - name: UNIT TEST (JEST)
    #   run: npm run test
      
    - name: SETUP ENV VARS
      run: NODE_ENV='staging'
      
    - name: RUN BUILD
      run: npm run build --if-present
      env:
        NODE_ENV: staging
        CI: false

  deploy: 
    needs: build
    runs-on: ubuntu-latest

    defaults:
        run:
          working-directory: ./server

    timeout-minutes: 1

    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v2
        
      - name: SETUP ENV VARIABLES
        run: NODE_ENV='staging'

      - name: BUILD ENV VARIABLES TO config/.env.staging
        run: echo $'${{ secrets.SERVER_ENV_STAGING}}' > ./config/.env.staging

      - name: CHECK ENV VARIABLES IN config/.env.staging
        run: cat ./config/.env.staging

      - name: HEROKU DEPLOY
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_STAGING_SERVER_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_STAGING_SERVER_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_STAGING_SERVER_EMAIL}}
          appdir: "./server"
          env_file: "./config/.env.staging"


